apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "currency-api-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "currency-api-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "currency-api-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "currency-api-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: CURRENCY_API_PATH_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: currency-api-config
                  key: CURRENCY_API_PATH_PREFIX
            - name: CURRENCY_API_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: currency-api-config
                  key: CURRENCY_API_LOG_LEVEL
          resources: {{- toYaml .Values.resources | nindent 12 }}

